/**
 * Builds the game as ONE self-contained HTML document for the Expo app in mobile/.
 *
 *   npm run build:mobile
 *
 * Everything (JS, CSS, fonts) is inlined, so the WebView needs no file access, no module loading over
 * file:// and no network. The result is written to mobile/src/gameHtml.ts as a string constant.
 */
import fs from 'node:fs';
import path from 'node:path';

import { build } from 'vite';

const root = path.resolve(import.meta.dirname, '..');
const outDir = path.join(root, 'dist-mobile');

await build({
  root,
  configFile: path.join(root, 'vite.config.ts'),
  mode: 'mobile',
  logLevel: 'warn',
  build: {
    outDir,
    emptyOutDir: true,
    assetsInlineLimit: Number.MAX_SAFE_INTEGER,
    cssCodeSplit: false,
    modulePreload: false,
  },
});

let html = fs.readFileSync(path.join(outDir, 'index.html'), 'utf8');
const read = (href) => fs.readFileSync(path.join(outDir, href.replace(/^\.?\//, '')), 'utf8');

// <link rel="stylesheet" href="./assets/x.css"> → <style>…</style>
html = html.replace(/<link rel="stylesheet"[^>]*href="([^"]+)"[^>]*>/g, (_, href) => `<style>${read(href)}</style>`);
// <script type="module" src="./assets/x.js"></script> → inline module
html = html.replace(/<script type="module"[^>]*src="([^"]+)"[^>]*><\/script>/g, (_, src) => {
  const js = read(src).replace(/<\/script/gi, '<\\/script');
  return `<script type="module">${js}</script>`;
});
// The favicon is irrelevant inside the app.
html = html.replace(/<link rel="icon"[^>]*>/g, '');

const leftovers = html.match(/(src|href)="\.?\/?assets\/[^"]+"/g);
if (leftovers) throw new Error(`Assets were not inlined: ${leftovers.join(', ')}`);

const target = path.join(root, 'mobile', 'src', 'gameHtml.ts');
fs.mkdirSync(path.dirname(target), { recursive: true });
fs.writeFileSync(
  target,
  `// Generated by scripts/build-mobile.mjs – do not edit. Run \`npm run build:mobile\` after changing the game.\n` +
    `/* eslint-disable */\nexport const GAME_HTML: string = ${JSON.stringify(html)};\n`,
);
console.log(`✔ mobile/src/gameHtml.ts (${(html.length / 1024).toFixed(0)} KB)`);
